# 2.3 Lab: Introduction to Python

## 2.3.2 Basic Commands

Python uses functions to perform operations

In [1]:
print("Hello", 11, "world")

Hello 11 world


In [2]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [3]:
3 + 5

8

### Adding two lists
Adding two lists results in concatenation

In [5]:
x = [3, 4, 5]
x

[3, 4, 5]

In [6]:
y = [6, 7, 8]
y

[6, 7, 8]

In [7]:
x + y

[3, 4, 5, 6, 7, 8]

## 2.3.3 Introduction to numerical python

In [2]:
import numpy as np

In [3]:
x = np.array([3, 4, 5])
y = np.array([6, 7, 8])

In [4]:
x + y

array([ 9, 11, 13])

In [5]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

The object `x` has several attributes or associated objects.

In [6]:
x.dtype

dtype('int64')

In [7]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [8]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [9]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [10]:
x.shape

(2, 2)

In [11]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [12]:
np.sum(x)

10

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])
x_reshape = x.reshape((2, 3))

In [14]:
x

array([1, 2, 3, 4, 5, 6])

In [15]:
x_reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x_reshape[0, 0]

1

In [17]:
x_reshape[1, 2]

6

In [18]:
x_reshape[0, 0] = 5

In [19]:
x_reshape

array([[5, 2, 3],
       [4, 5, 6]])

In [20]:
x

array([5, 2, 3, 4, 5, 6])

In [21]:
my_tuple = (1, 2, 3)
my_tuple[0] = 0

TypeError: 'tuple' object does not support item assignment

In [22]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [23]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [24]:
x ** 2

array([25,  4,  9, 16, 25, 36])

In [26]:
x ** 0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [27]:
x = np.random.normal(size=50)
x

array([ 0.33001153,  1.66097134,  1.30007743,  0.74859017, -1.59381409,
        1.40335892,  0.0407746 ,  1.17590416, -0.8293885 , -0.5971388 ,
       -0.25207198, -0.07000144,  1.21030769,  2.26568785,  0.44874835,
       -3.34131982, -0.53820424, -0.76341587,  0.36324755,  1.44025346,
       -0.83436463, -0.97820144, -0.03389795, -0.6077975 ,  1.46947852,
       -0.80007817, -0.81531032, -0.06482883, -1.02559847, -0.03362993,
       -1.34059276, -0.29183991, -0.94801427, -1.09973097, -0.15614629,
       -1.26079784,  0.76074262,  0.44423119, -1.04119331, -0.29186014,
        1.4987388 ,  0.33830768, -0.22386319,  1.59322381, -1.69675021,
        1.19507171, -0.09333368, -0.08904928,  1.85255731,  0.05444271])

In [28]:
y = x + np.random.normal(loc=50, scale=1, size = 50)

`loc` is the mean of the distribtion, `scale` is the standard deviation

In [29]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[9.75640933 6.62725575]
[  4.41934978 -10.09225078]


We use `np.random.default_rng` to set the seeds 

In [30]:
rng = np.random.default_rng(101)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(101)
print(rng2.normal(scale=5, size=2))

[ -3.9507625  -10.17312741]
[ -3.9507625  -10.17312741]


In [31]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [32]:
np.var(y)

2.7243406406465125

In [33]:
X = rng.standard_normal((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [34]:
X.mean(axis=0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [35]:
X.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])